"""Conversation → customer identity (docs/IDENTITY_IMPLEMENTATION_SPEC.md §2)."""
from app.services.identity.service import (
    BOUND,
    METHOD_IDENTITY,
    METHOD_PARENT,
    METHOD_UPSTREAM,
    UNBOUND,
    assert_document_bound,
    bind_chat,
    binding_out,
    chat_key,
    identity_block_of,
    is_unbound,
    list_bindings,
    list_unbound_chats,
    orders_for_identity,
    release_held,
    resolve_chat,
    resolve_for_document,
    unbind_identity,
)

__all__ = [
    "BOUND", "UNBOUND",
    "METHOD_IDENTITY", "METHOD_UPSTREAM", "METHOD_PARENT",
    "assert_document_bound",
    "bind_chat",
    "binding_out",
    "chat_key",
    "identity_block_of",
    "is_unbound",
    "list_bindings",
    "list_unbound_chats",
    "orders_for_identity",
    "release_held",
    "resolve_chat",
    "resolve_for_document",
    "unbind_identity",
]
